<?php

return [
    'specialty' => [
        'AI',
        'Software',
        'Cyber Security',
        'Network'
    ],
    'section' => [
        'Frontend',
        'Backend',
        'MobileDevelopment',
        'FullStack',
        'DBAnalysis',
        'DevOps',
        'GamesDevelopment',
        'SoftwareAnalysis',
        'QualityAssurance',
        'CloudArchitecture',
        'MachineLearning',
        'DeepLearning',
        'Robotics',
        'NaturalLanguageProcessing',
        'ExpertSystems',
        'FuzzyLogic',
        'ComputerVision',
        'DataScientist',
        'ArtificialGeneralIntelligence',
        'NaturalNetwork',
        'NetworkSecurity',
        'CloudSecurity',
        'EndPointSecurity',
        'MobileSecurity',
        'IoTSecurity',
        'ApplicationSecurity',
        'ZeroTrust',
        'NetworkAdministrators',
        'NetworkEngineer',
        'NetworkAnalyst',
        'SystemsAdministrators',
        'NetworkTechnician',
    ],
    'framework' => [
        'Flutter',
        'AngularJs',
        'ReactJs',
        'Laravel',
        'ReactNative',
        'Net',
        'jQuery',
        'Asp',
        'Django',
        'Xamarin',
        'BootStrap',
    ],
    'language' => [
        'Dart',
        'Php',
        'Java',
        'Cpp',
        'Python',
        'JavaScript',
        'TypeScript',
        'SQL',
        'Kotlin',
        'Swift',
        'Rust',
        'MatLab',
        'Scala',
    ]
];
